#!/bin/bash
# usage_examples.sh
# Examples of how to use the SAM custom path processor

echo "SAM Custom Path Processor Usage Examples"
echo "========================================"

echo ""
echo "1. Basic usage - process all images in a folder:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output"

echo ""
echo "2. Process with compression and size limits:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --compress --quality 75 --max-size 512"

echo ""
echo "3. Process with flat output structure (no folder hierarchy):"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --flat-output"

echo ""
echo "4. Memory-conservative settings for large images:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --points-per-side 16 --points-per-batch 32 \\"
echo "  --max-image-size 1024 --compress --quality 75"

echo ""
echo "5. Skip already processed images:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --skip-existing"

echo ""
echo "6. Force CPU processing (for CUDA issues):"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --force-cpu"

echo ""
echo "7. Example with your current dataset:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path ./anniedoris-design_qa-main/dataset \\"
echo "  --output-path ./sam_results \\"
echo "  --compress --quality 75 --max-size 512 \\"
echo "  --points-per-side 16 --points-per-batch 32"

echo ""
echo "8. Filter out all-white segments (default behavior):"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --filter-white --white-threshold 240 --white-ratio-threshold 0.95"

echo ""
echo "9. Disable white filtering:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --no-filter-white"

echo ""
echo "10. Filter both white and low-variance segments:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --input-path /path/to/your/images \\"
echo "  --output-path /path/to/output \\"
echo "  --filter-white --filter-low-variance \\"
echo "  --white-threshold 230 --variance-threshold 150"

echo ""
echo "11. Your specific command with white filtering:"
echo "python sam_custom_path_processor.py \\"
echo "  --checkpoint sam_vit_h_4b8939.pth \\"
echo "  --model-type vit_h \\"
echo "  --min-mask-region-area 10000 \\"
echo "  --points-per-side 8 --points-per-batch 1 \\"
echo "  --compress --quality 75 --max-size 512 \\"
echo "  --input-path ./anniedoris-design_qa-main/dataset/rule_compliance/rule_functional_performance_qa \\"
echo "  --output-path ./sam_results \\"
echo "  --filter-white --white-threshold 240"
